/*
 * Copyright Â© 2025 Devin B. Royal.
 * All Rights Reserved.
 */


logging:
  level: INFO
  format: json
  handlers:
    - file: setup.log

# # FULLY INJECTED by omniweave_full_inject.sh v1.0.0 at 2025-12-16T02:23:30Z
