/*
 * Copyright © 2025 Devin B. Royal.
 * All Rights Reserved.
 */


brand:
  name: OmniWeave OS
  seal: ◆
  colors:
    primary: #00FF00
    secondary: #0000FF

# # FULLY INJECTED by omniweave_full_inject.sh v1.0.0 at 2025-12-16T02:23:30Z
